name: streamlit_wrapper
description: A simple Flutter WebView shell for Streamlit apps.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.7
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true
